apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aidp-notify.fullname" . }}
  labels:
    {{- include "aidp-notify.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aidp-notify.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "aidp-notify.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: notify
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:
            - name: AIDP_SERVICE_NAME
              value: {{ .Values.env.aidpServiceName | quote }}
            - name: AIDP_DB_URL
              value: {{ .Values.env.aidpDbUrl | quote }}
            - name: AIDP_REDIS_URL
              value: {{ .Values.env.aidpRedisUrl | quote }}
            - name: AIDP_KAFKA_BROKERS
              value: {{ .Values.env.aidpKafkaBrokers | quote }}
            - name: AIDP_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "aidp-notify.fullname" . }}-secrets
                  key: jwt-secret
                  optional: false
            - name: AIDP_LOG_LEVEL
              value: {{ .Values.env.aidpLogLevel | quote }}
            - name: AIDP_ENV
              value: {{ .Values.env.aidpEnv | quote }}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      securityContext:
        fsGroup: 1000
